version: '3.3'
services:
  snake:
    image: 'kevinsasian/realestate_docker_repo:latest'
    environment:
      - "PORT:3000"
    ports:
      - "80:80"
    volumes:
      - ./:/usr/local/apache2/htdocs/